---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "{{ repo_name }}"
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main,feature/*,release/*]"
    pipelinesascode.tekton.dev/task: "[git-clone,gradle]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  podTemplate:
    securityContext:
      fsGroup: 65532
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    workspaces:
      - name: source
      - name: basic-auth
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: build
        runAfter: fetch-repository
        taskRef:
          name: gradle
        workspaces:
          - name: source
            workspace: source
          - name: maven-config
            workspace: maven-config
            mountPath: /home/gradle/.m2
        params:
          - name: GRADLE_IMAGE
            value: gradle:8.1.1-jdk17
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: maven-config
      projected:
        sources:
          - configMap:
              name: maven-settings
          - secret:
              name: maven-settings
